WINDOW_WID: 600
WINDOW_HEI: 600

image_container: ../images/container.jpg
image_awesomeface: ../images/awesomeface.png

simple_cube: ../model/simple_cube.txt
simple_sqad: ../model/simple_sqad.txt
simple_plne: ../model/simple_plne.txt

main_vs: ../shader/shader_vert/hello_framebuffer_vs.glsl
main_fs: ../shader/shader_frag/hello_framebuffer_fs.glsl

sqad_vs: ../shader/shader_vert/hello_screen_vs.glsl
sqad_fs: ../shader/shader_frag/hello_screen_fs.glsl

# sqad_vs: ../shader/shader_vert/shadertoy_common_vs.glsl
# sqad_fs: ../shader/shader_frag/shadertoy_home_fs.glsl
